version: 0.1
default:
  deploy:
    parameters:
      stack_name: "tree-admin"
      resolve_s3: true
      s3_prefix: "tree-admin"
      region: "us-east-1"
      capabilities: "CAPABILITY_IAM"
      image_repositories: []